### PR TITLE
libblant.c for BuildGraph and TinyGraph2Int

### PR DESCRIPTION
**Pull request by HBBrennan**

### CODE REVIEW

**Comment by waynebhayes** [comment]
Soo.... with the new pull, it works for me on 32-bit cygwin under Windows 7
or 10, but I get core dumps on 64-bit Linux on the openlab machines.  It
seems the make-canon-maps is failing to produce a full file; a bit of time
with the debugger suggests some data types are not the right size.  In
particular, inside BuildGraph, here:

34      void BuildGraph(TINY_GRAPH* G, int Gint)
35      {
36          int i, j, bitPos=0, k = G->n;

after the above line is executed, G->n is 2, but k is some huge 9-digit
number, even though it's just been set to something that is presumably
equal to 2.

can you check it on openlab (odin or some other 64-bit Linux box) and see
what's up?

**Comment by waynebhayes** [comment]
PS: this kind of thing is often related to misaligned or mis-sized types;
the compiler using catches those things and issues warnings, so be sure to
heed any compile-time wanings about mismatched prototypes.

**Comment by HBBrennan** [comment]
In the commit "tighten up data defs in sets and tinygraph; added faster
connectivity… " you changed TinySet to use a char instead of an int. My
code assigned an int using that variable. I believe this is what is causing
the issues. Should BuildGraph infer the number of nodes from how the
TinyGraph was allocated, or have it as a parameter?

**Comment by waynebhayes** [comment]
Oops.  Right.  My bad, sorry.

BuildGraph infers k from G->n, where G is the TinyGraph, so I don't think
it needs an extra parameter.

-- 
Wayne Hayes, Ph.D.
Associate Professor, Computer Science, University of California, Irvine
President Trump is a self-absorbed, self-serving, habitual liar. The former
two are opinion; the latter is fact. Examples (1)
http://foreignpolicy.com/2017/08/18/trumps-lies-about-james-comey-keep-unraveling
. (2) https://www.theguardian.com/us-news/trump-administration

**Pull request merged**
