### PR TITLE
Reorder ODV output to match ORCA ordering for k=4,5

### PR DESCRIPTION
**Pull request by HBBrennan**
Merge this if you want our ODV output in ORCA order for k=3,4,5
I added an additional array for connected orbits so we can iterate over that rather than all orbits when outputting ODV's. This enabled me to use another lookup table to output our orbits in the same ordering as ORCA. I verified the results are correct by generating graphs with 1 of each graphlet type and verifying the 2d arrays formed from our ODV output and ORCA's output casted to bools are equal. Since each node participates as an orbit in only one graphlet type, this ensures the orbits are in the same order.

### CODE REVIEW

**Comment by waynebhayes** [comment]
Yes, absolutely will merge.  Plus, that's an awesome candidate for a
regression test. Can you add it to the regression-test suite as well?  Just
create a directory under regression-tests, say  "orcaNumbering", put your
graphs in there, and create a shell script with any name ending in ".sh";
all .sh scipts in that dir will be run *with their current directory in the
main repo.*

--
Wayne Hayes, Ph.D.
Associate Professor of Computer Science, University of California, Irvine
Director, UCI-SDSU Joint Ph.D. Program in Computational Science (UCI side)
*The evidence is now incontrovertible that Russia interfered with the 2016
US Presidential election by manipulating public opinion with disinformation
via thousands of fake social media accounts. Why? Follow the money: Trump
has been laundering it for Russian billionaires, including Putin, for 20
years. Details and fact checking
at https://secure.avaaz.org/campaign/en/shocking_truth_about_trump/?bebhylb
<https://secure.avaaz.org/campaign/en/shocking_truth_about_trump/?bebhylb>.*
The opinions expressed in this email by Professor Hayes are his and his
alone, and are not meant to represent those of the University of California.

**Comment by waynebhayes** [comment]
Oh, and PS: the repo is currently slightly broken; another student is
working on reducing the memory footprint of the lookup tables to only
what's needed; they're halfway through but "make all" breaks. Should be
fixed by tomorrow.

--
Wayne Hayes, Ph.D.
Associate Professor of Computer Science, University of California, Irvine
Director, UCI-SDSU Joint Ph.D. Program in Computational Science (UCI side)
*The evidence is now incontrovertible that Russia interfered with the 2016
US Presidential election by manipulating public opinion with disinformation
via thousands of fake social media accounts. Why? Follow the money: Trump
has been laundering it for Russian billionaires, including Putin, for 20
years. Details and fact checking
at https://secure.avaaz.org/campaign/en/shocking_truth_about_trump/?bebhylb
<https://secure.avaaz.org/campaign/en/shocking_truth_about_trump/?bebhylb>.*
The opinions expressed in this email by Professor Hayes are his and his
alone, and are not meant to represent those of the University of California.

**Comment by waynebhayes** [comment]
don't we need it for k=3 as well?
--
Wayne Hayes, Ph.D.
Associate Professor of Computer Science, University of California, Irvine
Director, UCI-SDSU Joint Ph.D. Program in Computational Science (UCI side)
*The evidence is now incontrovertible that Russia interfered with the 2016
US Presidential election by manipulating public opinion with disinformation
via thousands of fake social media accounts. Why? Follow the money: Trump
has been laundering it for Russian billionaires, including Putin, for 20
years. Details and fact checking
at https://secure.avaaz.org/campaign/en/shocking_truth_about_trump/?bebhylb
<https://secure.avaaz.org/campaign/en/shocking_truth_about_trump/?bebhylb>.*
The opinions expressed in this email by Professor Hayes are his and his
alone, and are not meant to represent those of the University of California.

**Comment by waynebhayes** [comment]
Is there any reason line 300 of magictable.cpp is spiting out a zillion
copies of k?

**Comment by HBBrennan** [comment]
k=3 is correct without any changes needed.
Some debug printing from long ago I mistakenly skipped when removing. I'll track down why that happens and change it to an assertion for the invariant it's supposed to track.

**Comment by waynebhayes** [comment]
Ok thx
--
Wayne Hayes, Ph.D.
Associate Professor of Computer Science, University of California, Irvine
Director, UCI-SDSU Joint Ph.D. Program in Computational Science (UCI side)
*The evidence is now incontrovertible that Russia interfered with the 2016
US Presidential election by manipulating public opinion with disinformation
via thousands of fake social media accounts. Why? Follow the money: Trump
has been laundering it for Russian billionaires, including Putin, for 20
years. Details and fact checking
at https://secure.avaaz.org/campaign/en/shocking_truth_about_trump/?bebhylb
<https://secure.avaaz.org/campaign/en/shocking_truth_about_trump/?bebhylb>.*
The opinions expressed in this email by Professor Hayes are his and his
alone, and are not meant to represent those of the University of California.

**Pull request merged**
