### PR TITLE
Add regression tests for ODV output to match ORCA

### PR DESCRIPTION
**Pull request by HBBrennan**

### CODE REVIEW

**Comment by HBBrennan** [comment]
I should mention I assumed python3 was in the path with numpy installed.

**Comment by waynebhayes** [comment]
I'm seeing this on two different machines:

bayonet-09:BLANT$ ./regression-tests/orcaNumbering/test.sh
Testing ODV output matches ORCA for k=3
Testing ODV output matches ORCA for k=4
Testing ODV output matches ORCA for k=5
  File "regression-tests/orcaNumbering/test.py", line 8
    odv = np.loadtxt(f"{sys.argv[1]}/{k}.odv", delimiter = ' ',
usecols=range(1, num_connected_orbits[k]+1))
                                            ^
SyntaxError: invalid syntax

**Comment by HBBrennan** [comment]
I didn't realize openlab had such an outdated version of python. I was
relying on this printf for literals feature:
https://www.python.org/dev/peps/pep-0498/ added in Python 3.6 I'll change
it to be more backwards compatible.

**Comment by waynebhayes** [comment]
That's not openlab; it's my virtual machine that performs regression tests.
If it works on openlab and other "standard" locations, maybe all I need to
do is update the version of python on my virtual server. It has python
3.6.7. (I thought that was pretty recent?)

--
Wayne Hayes, Ph.D.
Associate Professor of Computer Science, University of California, Irvine
Director, UCI-SDSU Joint Ph.D. Program in Computational Science (UCI side)
*The evidence is now incontrovertible that Russia interfered with the 2016
US Presidential election by manipulating public opinion with disinformation
via thousands of fake social media accounts. Why? Follow the money: Trump
has been laundering it for Russian billionaires, including Putin, for 20
years. Details and fact checking
at https://secure.avaaz.org/campaign/en/shocking_truth_about_trump/?bebhylb
<https://secure.avaaz.org/campaign/en/shocking_truth_about_trump/?bebhylb>.*
The opinions expressed in this email by Professor Hayes are his and his
alone, and are not meant to represent those of the University of California.

**Comment by HBBrennan** [comment]
The feature was added in 3.6 so I'm not sure why you're getting that issue.
Could it be caused by the newlines in the snippet you've pasted?
The default python3 version for openlab (without loading any modules) is
3.4.9. I can easily switch to a more backwards compatible string formatting
syntax if necessary.

**Comment by waynebhayes** [comment]
Sure, backwards compatible is good. Or just avoid python entirely. Can it
be a shell or awk script?
--
Wayne Hayes, Ph.D.
Associate Professor of Computer Science, University of California, Irvine
Director, UCI-SDSU Joint Ph.D. Program in Computational Science (UCI side)
*The evidence is now incontrovertible that Russia interfered with the 2016
US Presidential election by manipulating public opinion with disinformation
via thousands of fake social media accounts. Why? Follow the money: Trump
has been laundering it for Russian billionaires, including Putin, for 20
years. Details and fact checking
at https://secure.avaaz.org/campaign/en/shocking_truth_about_trump/?bebhylb
<https://secure.avaaz.org/campaign/en/shocking_truth_about_trump/?bebhylb>.*
The opinions expressed in this email by Professor Hayes are his and his
alone, and are not meant to represent those of the University of California.

**Pull request merged**
